org.gradle.jvmargs=-Xmx2G
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.daemon=false

minecraft_version=1.21.1
neo_version=21.1.229
loader_version_range=[4,)

mod_id=voxy_transformer
mod_name=Voxy_Transformer
mod_license=All Rights Reserved
mod_version=1.1.1
mod_group_id=com.aerosmp.inittransformer

voxy_target_jar=target_jar/ASMP_voxy-0.2.213-beta+1.21.1-neoforge.jar

voxy_source_filename=voxy-0.2.9-alpha-1.21.11.jar
voxy_source_sha256=7a640f888c11f33d765dd6b7e6666538d04c1a5ea0e2160bd02acfa5ad6f6ef4
