org.gradle.jvmargs=-Xmx2G
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.daemon=false

minecraft_version=1.21.1
neo_version=21.1.229
parchment_mappings_version=2024.11.17
loader_version_range=[4,)

mod_id=voxy_transformer
mod_name=Voxy_Transformer
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=com.aerosmp.inittransformer

voxy_target_jar=used_jar/voxy-0.2.15-beta+1.21.1-neoforge.jar

voxy_source_url=https://cdn.modrinth.com/data/fxxUqruK/versions/1rOxxZT5/voxy-0.2.9-alpha-1.21.11.jar
voxy_source_filename=voxy-0.2.9-alpha-1.21.11.jar
voxy_source_size=12612849
voxy_source_sha1=eee7eeee8ae1c5be118d0cb57683baf2533a67d2
voxy_source_sha256=7a640f888c11f33d765dd6b7e6666538d04c1a5ea0e2160bd02acfa5ad6f6ef4
voxy_source_sha512=6d85e327b5e32b8d8a33c561bbeef92f66e560c0fa52778207a80bd9834e4ce5c398c5d75b83224ba66a599fe9b1308c36c875f78e04d896399f1fa74a2cc21f
